version: '3.8'

services:
  grafana:
    image: grafana/grafana:11.0.0
    container_name: go-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:2.9.0
    container_name: go-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      # Mount file config mới
      - ./system/loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki # Vẫn cần local để lưu index tạm thời (cache)
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
      - minio

  promtail:
    image: grafana/promtail:2.9.0
    container_name: go-promtail
    restart: unless-stopped
    volumes:
      - ./internal/logs:/var/log
      - ./system/promtail/promtail.config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  # Service MinIO (Giả lập AWS S3)
  minio:
    image: minio/minio:latest
    container_name: go-minio
    restart: unless-stopped
    ports:
      - "9000:9000"  # API Port (Loki sẽ đẩy log vào đây)
      - "9001:9001"  # Console Port (Giao diện web để em quản lý bucket)
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  grafana-data:
  loki-data:
  minio-data: