// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Order struct {
	OrderID     string
	Uuid        string
	OrderDate   time.Time
	TotalAmount string
	Status      string
}

type User struct {
	Uuid        string
	UserName    string
	Email       string
	PhoneNumber sql.NullString
	Password    string
}
