// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (order_id, uuid, order_date, total_amount, status) VALUES ($1, $2, $3, $4, $5)
`

type CreateOrderParams struct {
	OrderID     string
	Uuid        string
	OrderDate   time.Time
	TotalAmount string
	Status      string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder,
		arg.OrderID,
		arg.Uuid,
		arg.OrderDate,
		arg.TotalAmount,
		arg.Status,
	)
	return err
}

const createUsers = `-- name: CreateUsers :exec

INSERT INTO users (uuid, user_name, email, phone_number, password) VALUES ($1, $2, $3, $4, $5)
`

type CreateUsersParams struct {
	Uuid        string
	UserName    string
	Email       string
	PhoneNumber sql.NullString
	Password    string
}

// Tệp tin query.sql này chủ yếu chứa các câu lệnh thực thi SQL
func (q *Queries) CreateUsers(ctx context.Context, arg CreateUsersParams) error {
	_, err := q.db.ExecContext(ctx, createUsers,
		arg.Uuid,
		arg.UserName,
		arg.Email,
		arg.PhoneNumber,
		arg.Password,
	)
	return err
}

const getAllOrders = `-- name: GetAllOrders :many
SELECT order_id, uuid, order_date, total_amount, status FROM orders
`

func (q *Queries) GetAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderID,
			&i.Uuid,
			&i.OrderDate,
			&i.TotalAmount,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserss = `-- name: GetAllUserss :many
SELECT uuid, user_name, email, phone_number, password FROM users
`

func (q *Queries) GetAllUserss(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserss)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Uuid,
			&i.UserName,
			&i.Email,
			&i.PhoneNumber,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT order_id, uuid, order_date, total_amount, status FROM orders WHERE order_id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, orderID string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.Uuid,
		&i.OrderDate,
		&i.TotalAmount,
		&i.Status,
	)
	return i, err
}

const getUsersByID = `-- name: GetUsersByID :one
SELECT uuid, user_name, email, phone_number, password FROM users WHERE uuid = $1
`

func (q *Queries) GetUsersByID(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUsersByID, uuid)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.UserName,
		&i.Email,
		&i.PhoneNumber,
		&i.Password,
	)
	return i, err
}
